base:
 duration: 3
 overwrite: True
 fps: 30
 batch_size: 4
 keyboard_detection: True

directory:
 video: /Users/bubz/Developer/master-project/prototype/dvc-test-1/dyadiccnn3d/data/raw/video

 keyboard_detection: /Users/bubz/Developer/master-project/prototype/dvc-test-1/dyadiccnn3d/data/raw/keyboard_detection

files:
 videos:
  - GC2L2P-Jun28-B-Phuong_q2_01-08.mp4
  - GC2L2P-Jun28-B-Phuong_q2_02-08.mp4
  - GC2L2P-Jun28-B-Phuong_q2_03-08.mp4
  - GC2L2P-Jun28-B-Phuong_q2_04-08.mp4
  - GC2L2P-Jun28-B-Phuong_q2_05-08.mp4
  - GC2L2P-Jun28-B-Phuong_q2_06-08.mp4
  - GC2L2P-Jun28-B-Phuong_q2_07-08.mp4
  - GC2L2P-Jun28-B-Phuong_q2_08-08.mp4
    
 keyboard_detections:
  - GC2L2P-Jun28-B-Phuong_q2_01-08.csv
  - GC2L2P-Jun28-B-Phuong_q2_02-08.csv
  - GC2L2P-Jun28-B-Phuong_q2_03-08.csv
  - GC2L2P-Jun28-B-Phuong_q2_04-08.csv
  - GC2L2P-Jun28-B-Phuong_q2_05-08.csv
  - GC2L2P-Jun28-B-Phuong_q2_06-08.csv
  - GC2L2P-Jun28-B-Phuong_q2_07-08.csv
  - GC2L2P-Jun28-B-Phuong_q2_08-08.csv
    
 roi: /Users/bubz/Developer/master-project/prototype/dvc-test-1/dyadiccnn3d/data/raw/region/video_roi.csv

 session_props: /Users/bubz/Developer/master-project/prototype/dvc-test-1/dyadiccnn3d/data/raw/region/properties_session.csv

generate_proposal:
 output_dir: /Users/bubz/Developer/master-project/prototype/dvc-test-1/dyadiccnn3d/data/interim
 output_file: G-C2L2P-Jun28-B-Phuong_q2_tyrp_only_roi.csv
 overwrite: True

extract_proposal:
 output_dir: /Users/bubz/Developer/master-project/prototype/dvc-test-1/dyadiccnn3d/data/processed
 overwrite: True

classify_proposal:
  output_dir: /Users/bubz/Developer/master-project/prototype/dvc-test-1/dyadiccnn3d/data/processed
  output_dir_classified: /Users/bubz/Developer/master-project/prototype/dvc-test-1/dyadiccnn3d/data/processed/proposals_kbdet_classified
  output_file_detection: G-C2L2P-Jun28-B-Phuong_q2_tynty-roi-ours-final-output-kbdet.csv
  output_file_no_detection: G-C2L2P-Jun28-B-Phuong_q2_tynty-roi-ours-final-output.csv
  overwrite: True

neural_network:
 input_shape: [3, 90, 224, 224]
 checkpoint: /Users/bubz/Developer/master-project/prototype/dvc-test-1/dyadiccnn3d/data/raw/region/best_epoch53.pth
 depth: 4
 gpu: False
 overwrite: True



