#Params paths have been adjusted for the remote server in the lab. Add os.cwd() + path for all on this page.
# Or add absolute path instead
base:
 duration: 3
 overwrite: True
 fps: 30
 batch_size: 4
 num_workers: 4
 keyboard_detection: True

directory:
 video: data/raw/video

 keyboard_detection: data/raw/keyboard_detection

files:
 videos:
  - GC2L2P-Jun28-B-Phuong_q2_01-08.mp4
  - GC2L2P-Jun28-B-Phuong_q2_02-08.mp4
  - GC2L2P-Jun28-B-Phuong_q2_03-08.mp4
  - GC2L2P-Jun28-B-Phuong_q2_04-08.mp4
  - GC2L2P-Jun28-B-Phuong_q2_05-08.mp4
  - GC2L2P-Jun28-B-Phuong_q2_06-08.mp4
  - GC2L2P-Jun28-B-Phuong_q2_07-08.mp4
  - GC2L2P-Jun28-B-Phuong_q2_08-08.mp4
    
 keyboard_detections:
  - GC2L2P-Jun28-B-Phuong_q2_01-08.csv
  - GC2L2P-Jun28-B-Phuong_q2_02-08.csv
  - GC2L2P-Jun28-B-Phuong_q2_03-08.csv
  - GC2L2P-Jun28-B-Phuong_q2_04-08.csv
  - GC2L2P-Jun28-B-Phuong_q2_05-08.csv
  - GC2L2P-Jun28-B-Phuong_q2_06-08.csv
  - GC2L2P-Jun28-B-Phuong_q2_07-08.csv
  - GC2L2P-Jun28-B-Phuong_q2_08-08.csv
    
 roi: data/raw/region/video_roi.csv

 session_props: data/raw/region/properties_session.csv

generate_proposal:
 output_dir: data/interim
 output_file: G-C2L2P-Jun28-B-Phuong_q2_tyrp_only_roi.csv
 overwrite: False

extract_proposal:
 output_dir: data/processed
 overwrite: False

classify_proposal:
  output_dir: data/processed
  output_dir_classified: data/processed/proposals_kbdet_classified
  output_file_detection: G-C2L2P-Jun28-B-Phuong_q2_tynty-roi-ours-final-output-kbdet.csv
  output_file_no_detection: G-C2L2P-Jun28-B-Phuong_q2_tynty-roi-ours-final-output.csv
  overwrite: True

neural_network:
 input_shape: [3, 90, 224, 224]
 checkpoint: data/raw/region/best_epoch53.pth
 depth: 4
 gpu: True
 overwrite: True



